version: '3.8'
services:

  postgres:
    image: postgres:latest
    volumes:
      - bs-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${BS_POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - "${BS_POSTGRES_PORT}:${BS_POSTGRES_PORT}"

  book-service:
    image: go-book-service
    build:
      context: ./book-service
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${BS_POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${BS_POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${BS_SERVER_PORT}:${BS_SERVER_PORT}"
    depends_on:
      - postgres
    command: air ./cmd/main.go -b 0.0.0.0

volumes:
  bs-data: