version: '1'
services:
  book-service:
    build:
      context: ./book-service
      dockerfile: Dockerfile
    ports:
      - "$PORT:$PORT"
    env_file: .env

  review-service:
    build:
      context: ./review-service 
      dockerfile: Dockerfile
    ports:
      - "$PORT:$PORT"
    env_file: .env
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "$PORT:$PORT"
    env_file: .env
