version: '1'
services:
  book-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: book_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  book-service:
    build:
      context: ./book-service
      dockerfile: Dockerfile
    env_file: ./book-service/.env
    ports:
      - "8080:8080"
    depends_on:
      - book-postgres

  review-service:
    build:
      context: ./review-service 
      dockerfile: Dockerfile
    env_file: ./review-service/.env
    ports:
      - "8082:8082"
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    env_file: ./user-service/.env
    ports:
      - "8081:8081"
