version: '3.8'
services:

  bookdb:
   extends:
      file: ./book-service/service.yml
      service: postgres
  bookservice:
    extends:
      file: ./book-service/service.yml
      service: service
    depends_on:
      - bookdb

  reviewdb:
   extends:
      file: ./review-service/service.yml
      service: postgres
  reviewservice:
    extends:
      file: ./review-service/service.yml
      service: service
    depends_on:
      - reviewdb
  
  userdb:
   extends:
      file: ./user-service/service.yml
      service: postgres
  userservice:
    extends:
      file: ./user-service/service.yml
      service: service
    depends_on:
      - userdb

volumes:
  bs-data:
  rs-data:
  us-data: