version: '1'
services:

  book-service:
    image: go-book-service
    build:
      context: ./book-service
      dockerfile: Dockerfile
    env_file: ./book-service/.env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB: bs
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    
  postgres:
    image: postgres:15
    volumes:
      - bs-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"

volumes:
  bs-data: