version: '1'

services:
  book-postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: book_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
  go-book-service:
    image: go-book-service
    build:
      context: ./book-service
      dockerfile: Dockerfile
    env_file: ./book-service/.env
    ports:
      - "8090:8080"
    depends_on:
      - book-postgres
