version: '1'

services:
  go-book-postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: book_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sudeki12
      POSTGRES_HOST: go-book-postgres
      POSTGRES_PORT: 5432
    networks: 
      - test-network
  book-service:
    image: go-book-service
    build:
      context: ./book-service
      dockerfile: Dockerfile
    env_file: ./book-service/.env
    environment:
      POSTGRES_DB: book_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sudeki12
      POSTGRES_HOST: go-book-postgres
      POSTGRES_PORT: 5432
    networks: 
      - test-network
    ports:
      - "8080:8080"
    depends_on:
      - go-book-postgres

networks: # явно объявленные сети
  test-network:
    driver: bridge
