services:

  kafka:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      KAFKA_CFG_NODE_ID: ${KAFKA_CFG_NODE_ID}
      KAFKA_CFG_PROCESS_ROLES: ${KAFKA_CFG_PROCESS_ROLES}
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}

      KAFKA_CFG_LISTENERS: ${KAFKA_CFG_LISTENERS}
      KAFKA_CFG_ADVERTISED_LISTENERS: ${KAFKA_CFG_ADVERTISED_LISTENERS}
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: ${KAFKA_CFG_CONTROLLER_LISTENER_NAMES}
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: ${KAFKA_CFG_INTER_BROKER_LISTENER_NAME}

  postgres:
    image: postgres:latest
    volumes:
      - bs-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${BS_POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - "${EXT_BS_POSTGRES_PORT}:${POSTGRES_PORT}"

  service:
    image: book-service
    build:
      context: ./book-service
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: ${BS_SERVER_PORT}
      POSTGRES_HOST: ${BS_POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${BS_POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${BS_SERVER_PORT}:${BS_SERVER_PORT}"
    command: air ./cmd/main.go -b 0.0.0.0

volumes:
  kafka_data:
    driver: local